# Generated by Django 3.0.2 on 2020-01-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='hex_id',
            field=models.CharField(default='ed71cad36dbc4e139c71b6f289f3a6b6', max_length=32),
        ),
    ]
