# Generated by Django 3.0.2 on 2020-01-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_web', '0002_auto_20200116_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='script',
            field=models.FileField(default='playbook/test.yml', upload_to='playbook/3a09c4298b484f529c6aa2d7079cb1c7.yml'),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='hex_id',
            field=models.CharField(max_length=32),
        ),
    ]
