# Generated by Django 3.0.2 on 2020-01-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_web', '0003_auto_20200116_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='script',
            field=models.FileField(default='playbook/test.yml', upload_to='playbook/'),
        ),
    ]
