# Generated by Django 3.0.2 on 2020-01-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_web', '0004_auto_20200116_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbook',
            name='hex_id',
        ),
    ]
