# Generated by Django 3.0.2 on 2020-01-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_web', '0005_remove_playbook_hex_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbook',
            name='hosts',
        ),
        migrations.AlterField(
            model_name='playbook',
            name='script',
            field=models.FileField(default='test.yml', upload_to='playbooks/'),
        ),
    ]
