# Generated by Django 3.0.2 on 2020-01-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_web', '0006_auto_20200117_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='playbook',
            name='script',
            field=models.FileField(default='test.yml', upload_to=''),
        ),
    ]
